<?php

/**
 * Created by PhpStorm.
 * User: Matheus Piciolli
 * Date: 10/10/2016
 * Time: 21:53
*/
    class Enderecos extends HelperDataBase
    {
        public function CreateEnderecos($Data)
        {
            return parent::Create("enderecos", $Data); // TODO: Change the autogenerated stub
        }

        public function ReadEnderecos($Condition)
        {
            return parent::Read("enderecos", $Condition); // TODO: Change the autogenerated stub
        }

        public function UpdateEnderecos($Field, $NewValue, $Id)
        {
            return parent::Update("enderecos", $Field, $NewValue, $Id); // TODO: Change the autogenerated stub
        }

        public function DeleteEnderecos($Condition)
        {
            return parent::Delete("enderecos", $Condition); // TODO: Change the autogenerated stub
        }
    }
?>