<?php

/**
 * Created by PhpStorm.
 * User: Matheus Piciolli
 * Date: 10/10/2016
 * Time: 21:52
 */
    class Experiencias extends HelperDataBase
    {
        private $idExperiencia;
        private $descricao;
        private $dataInicio;
        private $dataSaida;
        private $cargo;
        private $codAluno;

        public function CreateExperiencias($Data)
        {
            return parent::Create("experiencias", $Data); // TODO: Change the autogenerated stub
        }

        public function ReadExperiencias($Condition)
        {
            return parent::Read("experiencias", $Condition); // TODO: Change the autogenerated stub
        }

        public function UpdateExperiencias($Field, $NewValue, $Id)
        {
            return parent::Update("experiencias", $Field, $NewValue, $Id); // TODO: Change the autogenerated stub
        }

        public function DeleteExperiencias($Condition)
        {
            return parent::Delete("experiencias", $Condition); // TODO: Change the autogenerated stub
        }

        /**
         * @return mixed
         */
        public function getIdExperiencia()
        {
            return $this->idExperiencia;
        }

        /**
         * @param mixed $idExperiencia
         */
        public function setIdExperiencia($idExperiencia)
        {
            $this->idExperiencia = $idExperiencia;
        }

        /**
         * @return mixed
         */
        public function getDescricao()
        {
            return $this->descricao;
        }

        /**
         * @param mixed $descricao
         */
        public function setDescricao($descricao)
        {
            $this->descricao = $descricao;
        }

        /**
         * @return mixed
         */
        public function getDataInicio()
        {
            return $this->dataInicio;
        }

        /**
         * @param mixed $dataInicio
         */
        public function setDataInicio($dataInicio)
        {
            $this->dataInicio = $dataInicio;
        }

        /**
         * @return mixed
         */
        public function getDataSaida()
        {
            return $this->dataSaida;
        }

        /**
         * @param mixed $dataSaida
         */
        public function setDataSaida($dataSaida)
        {
            $this->dataSaida = $dataSaida;
        }

        /**
         * @return mixed
         */
        public function getCargo()
        {
            return $this->cargo;
        }

        /**
         * @param mixed $cargo
         */
        public function setCargo($cargo)
        {
            $this->cargo = $cargo;
        }

        /**
         * @return mixed
         */
        public function getCodAluno()
        {
            return $this->codAluno;
        }

        /**
         * @param mixed $codAluno
         */
        public function setCodAluno($codAluno)
        {
            $this->codAluno = $codAluno;
        }

    }
?>