<?php

/**
 * Created by PhpStorm.
 * User: Matheus Piciolli
 * Date: 10/10/2016
 * Time: 21:51
 */
    class Formacoes extends HelperDataBase
    {
        public function CreateFormacoes($Data)
        {
            return parent::Create("formacoes", $Data); // TODO: Change the autogenerated stub
        }

        public function ReadFormacoes($Condition)
        {
            return parent::Read("formacoes", $Condition); // TODO: Change the autogenerated stub
        }

        public function UpdateFormacoes($Field, $NewValue, $Id)
        {
            return parent::Update("formacoes", $Field, $NewValue, $Id); // TODO: Change the autogenerated stub
        }

        public function DeleteFormacoes( $Condition)
        {
            return parent::Delete("formacoes", $Condition); // TODO: Change the autogenerated stub
        }
    }
?>