<?php
    require_once "DataBase.class.php";
    require_once "HelperDataBase.class.php";
/**
 * Created by PhpStorm.
 * User: Matheus Piciolli
 * Date: 10/10/2016
 * Time: 21:51
 */
    class Telefones extends HelperDataBase
    {
        private $idTelefone;
        private $telefone;
        private $tipo;
        private $codAluno;

        public function CreateTelefones($Data)
        {
            return parent::Create("telefones", $Data); // TODO: Change the autogenerated stub
        }

        public function ReadTelefones($Condition)
        {
            return parent::Read("telefones", $Condition); // TODO: Change the autogenerated stub
        }

        public function UpdateTelefones($Field, $NewValue, $Id)
        {
            return parent::Update("telefones", $Field, $NewValue, $Id); // TODO: Change the autogenerated stub
        }

        public function DeleteTelefones($Condition)
        {
            return parent::Delete("telefones", $Condition); // TODO: Change the autogenerated stub
        }

        /**
         * @return mixed
         */
        public function getIdTelefone()
        {
            return $this->idTelefone;
        }

        /**
         * @param mixed $idTelefone
         */
        public function setIdTelefone($idTelefone)
        {
            $this->idTelefone = $idTelefone;
        }

        /**
         * @return mixed
         */
        public function getTelefone()
        {
            return $this->telefone;
        }

        /**
         * @param mixed $telefone
         */
        public function setTelefone($telefone)
        {
            $this->telefone = $telefone;
        }

        /**
         * @return mixed
         */
        public function getTipo()
        {
            return $this->tipo;
        }

        /**
         * @param mixed $tipo
         */
        public function setTipo($tipo)
        {
            $this->tipo = $tipo;
        }

        /**
         * @return mixed
         */
        public function getCodAluno()
        {
            return $this->codAluno;
        }

        /**
         * @param mixed $codAluno
         */
        public function setCodAluno($codAluno)
        {
            $this->codAluno = $codAluno;
        }

    }
?>