<?php
    require_once "DataBase.class.php";
    require_once "HelperDataBase.class.php";
/**
 * Created by PhpStorm.
 * User: Matheus Piciolli
 * Date: 10/10/2016
 * Time: 21:53
*/
    class Enderecos extends HelperDataBase
    {
        public function CreateEnderecos($Data)
        {
            return parent::Create("enderecos", $Data); // TODO: Change the autogenerated stub
        }

        public function ReadEnderecos($Condition)
        {
            return parent::Read("enderecos", $Condition); // TODO: Change the autogenerated stub
        }

        public function UpdateEnderecos($Field, $NewValue, $Condition)
        {
            return parent::Update("enderecos", $Field, $NewValue, $Condition); // TODO: Change the autogenerated stub
        }

        public function DeleteEnderecos($Condition)
        {
            return parent::Delete("enderecos", $Condition); // TODO: Change the autogenerated stub
        }
    }
?>