<?php

/**
 * Created by PhpStorm.
 * User: Desenvolvedor
 * Date: 22/09/2016
 * Time: 21:26
 */
    class ModelUsuario extends HelperDataBase
    {
        public function CreateUsuario($Data)
        {
            return parent::Create("usuario", $Data);
        }

        public function ReadUsuario($Condition)
        {
            return parent::Read("usuario", $Condition);
        }

        public function UpdateUsuario($Field, $NewValue, $Id)
        {
            return parent::Update("usuario", $Field, $NewValue, $Id); // TODO: Change the autogenerated stub
        }

        public function DeleteUsuario($Condition)
        {
            return parent::Delete("usuario", $Condition); // TODO: Change the autogenerated stub
        }
    }

?>