<?php

/**
 * Created by PhpStorm.
 * User: Desenvolvedor
 * Date: 22/09/2016
 * Time: 21:34
 */
    class ModelVaga extends HelperDataBase
    {
        public function CreateVaga($Data)
        {
            return parent::Create("vaga", $Data); // TODO: Change the autogenerated stub
        }

        public function ReadVaga($Condition)
        {
            return parent::Read("vaga", $Condition); // TODO: Change the autogenerated stub
        }

        public function UpdateVaga($Field, $NewValue, $Id)
        {
            return parent::Update("vaga", $Field, $NewValue, $Id); // TODO: Change the autogenerated stub
        }

        public function DeleteVaga($Condition)
        {
            return parent::Delete("vaga", $Condition); // TODO: Change the autogenerated stub
        }
    }

?>