<?php

/**
 * Created by PhpStorm.
 * User: Desenvolvedor
 * Date: 22/09/2016
 * Time: 21:26
 */
    class ModelUsuario extends HelperDataBase
    {
        private $idUsuario;
        private $email;
        private $nivel;
        private $senha;

        public function CreateUsuario($Data)
        {
            return parent::Create("usuario", $Data);
        }

        public function ReadUsuario($Condition)
        {
            return parent::Read("usuario", $Condition);
        }

        public function UpdateUsuario($Field, $NewValue, $Id)
        {
            return parent::Update("usuario", $Field, $NewValue, $Id); // TODO: Change the autogenerated stub
        }

        public function DeleteUsuario($Condition)
        {
            return parent::Delete("usuario", $Condition); // TODO: Change the autogenerated stub
        }

        /**
         * @return mixed
         */
        public function getIdUsuario()
        {
            return $this->idUsuario;
        }

        /**
         * @param mixed $idUsuario
         */
        public function setIdUsuario($idUsuario)
        {
            $this->idUsuario = $idUsuario;
        }

        /**
         * @return mixed
         */
        public function getEmail()
        {
            return $this->email;
        }

        /**
         * @param mixed $email
         */
        public function setEmail($email)
        {
            $this->email = $email;
        }

        /**
         * @return mixed
         */
        public function getNivel()
        {
            return $this->nivel;
        }

        /**
         * @param mixed $nivel
         */
        public function setNivel($nivel)
        {
            $this->nivel = $nivel;
        }

        /**
         * @return mixed
         */
        public function getSenha()
        {
            return $this->senha;
        }

        /**
         * @param mixed $senha
         */
        public function setSenha($senha)
        {
            $this->senha = $senha;
        }

    }

?>