<?php
    require_once "DataBase.class.php";
    require_once "HelperDataBase.class.php";
/**
 * Created by PhpStorm.
 * User: Desenvolvedor
 * Date: 22/09/2016
 * Time: 21:34
 */

    class Candidatouse extends HelperDataBase
    {
        public function CreateCandidatouse($Data)
        {
            return parent::Create("candidatouse", $Data); // TODO: Change the autogenerated stub
        }

        public function ReadCandidatouse($Condition)
        {
            return parent::Read("candidatouse", $Condition); // TODO: Change the autogenerated stub
        }

        public function UpdateCandidatouse($Field, $NewValue, $Id)
        {
            return parent::Update("candidatouse", $Field, $NewValue, $Id); // TODO: Change the autogenerated stub
        }

        public function DeleteCandidatouse($Condition)
        {
            return parent::Delete("candidatouse", $Condition); // TODO: Change the autogenerated stub
        }
    }

?>
