<?php

/**
 * Created by PhpStorm.
 * User: Matheus Piciolli
 * Date: 10/10/2016
 * Time: 21:51
 */
    class Telefones extends HelperDataBase
    {
        public function CreateTelefones($Data)
        {
            return parent::Create("telefones", $Data); // TODO: Change the autogenerated stub
        }

        public function ReadTelefones($Condition)
        {
            return parent::Read("telefones", $Condition); // TODO: Change the autogenerated stub
        }

        public function UpdateTelefones($Field, $NewValue, $Id)
        {
            return parent::Update("telefones", $Field, $NewValue, $Id); // TODO: Change the autogenerated stub
        }

        public function DeleteTelefones($Condition)
        {
            return parent::Delete("telefones", $Condition); // TODO: Change the autogenerated stub
        }
    }
?>